# Generated by Django 5.2.5 on 2026-09-27 23:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Escuderia',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Piloto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('numero', models.IntegerField(help_text='Número del dorsal')),
                ('edad', models.IntegerField()),
                ('titulos', models.IntegerField(default=0, help_text='Solo campeonatos de MotoGP (no Moto2 ni Moto3)')),
                ('imagen_url', models.CharField(blank=True, help_text='Link de internet o nombre de archivo local', max_length=500, null=True)),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='motogpApp.categoria')),
                ('escuderia', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='motogpApp.escuderia')),
            ],
        ),
    ]
